import os
from subprocess import call, Popen, PIPE, STDOUT


def makemrr(*result):
    print("Reordering and generating mirror file from result")
    data = """### Automatically generated by mirror-check-speed on github
### \t \t https://github.com/ronanhansel/mirror-check-speed
###
### You can contribute by creating a pull request or report bugs or irritance there
### Have a good day!

"""
    for i in result[0]:
        data += '\n' + "Server = " + (result[1])[i]
    if os.path.exists("mirrorlist"):
        os.remove("mirrorlist")
    with open("mirrorlist", "x") as m:
        m.write(data)
    print("Do you want the file to be saved (and override if exist) to /etc/pacman.d/mirrorlist?")
    print("This is highly experimental for non-pacman users and if you're not using arch mirrors, only proceed if you know what you're doing")
    print("If you select no (n) the file will be stored inside of your cwd")
    while True:
        ans = input('(y/n) ')
        if ans == "y":
            event = Popen(f"sudo mv {os.getcwd()}/mirrorlist /etc/pacman.d/mirrorlist", shell=True, stdin=PIPE, stdout=PIPE,
                stderr=STDOUT)
            print(event.communicate()[0].decode("utf-8"))
            print('Successfully saved file')
            break
        elif ans == "n":
            print('Saved mirrorlist in ' + os.getcwd())
            return
        else:
            print('Please enter a valid option')
    
